errand-config:
  delete-prior-space:
    post-deploy-state: true
  delete-space:
    pre-delete-state: true
  migrate-route:
    post-deploy-state: true
  push-apps:
    post-deploy-state: true
  smoke-tests:
    post-deploy-state: true
network-properties:
  network:
    name: services
  other_availability_zones:
  - name: zone-1
  - name: zone-2
  - name: zone-3
  singleton_availability_zone:
    name: zone-1
product-name: apmPostgres
product-properties:
  .errand-runner.ingestor_instance_count:
    value: 1
  .errand-runner.logs_queue_instance_count:
    value: 1
  .errand-runner.logs_queue_max_retention_percentage:
    value: 85
  .errand-runner.logs_queue_retention_percentage_interval:
    value: 1h
  .errand-runner.logs_retention_window:
    value: 14
  .errand-runner.metrics_queue_instance_count:
    value: 1
  .errand-runner.metrics_retention_window:
    value: 14
  .errand-runner.push_apps_log_level:
    value: error
  .errand-runner.server_instance_count:
    value: 1
  .mysql.roadmin_password:
    value: {}
resource-config:
  errand-runner:
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: false
    max_in_flight: 1
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  mysql:
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: false
    max_in_flight: 1
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  postgres:
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: false
    max_in_flight: 1
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  redis:
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: false
    max_in_flight: 1
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
syslog-properties:
  address: null
  custom_rsyslog_configuration: null
  enabled: false
  forward_debug_logs: false
  permitted_peer: null
  port: null
  queue_size: null
  ssl_ca_certificate: null
  tls_enabled: false
  transport_protocol: tcp
