product-name: p-bosh
network-properties:
  network:
    name: infrastructure
  other_availability_zones: []
  singleton_availability_zone:
    name: zone-1
resource-config:
  compilation:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: false
    swap_as_percent_of_memory_size: automatic
  director:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: false
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
syslog-properties:
  address: null
  custom_rsyslog_configuration: null
  enabled: false
  forward_debug_logs: false
  permitted_peer: null
  port: null
  queue_size: null
  ssl_ca_certificate: null
  tls_enabled: false
  transport_protocol: tcp

