errand-config:
  delete-space:
    pre-delete-state: true
  push-apps:
    post-deploy-state: true
  smoke-tests:
    post-deploy-state: true
network-properties:
  network:
    name: services
  other_availability_zones:
  - name: zone-1
  - name: zone-2
  - name: zone-3
  service_network:
    name: services
  singleton_availability_zone:
    name: zone-1
product-name: p-healthwatch
product-properties:
  .healthwatch-forwarder.boshhealth_instance_count:
    value: 1
  .healthwatch-forwarder.boshtasks_instance_count:
    value: 2
  .healthwatch-forwarder.canary_instance_count:
    value: 2
  .healthwatch-forwarder.cli_instance_count:
    value: 2
  .healthwatch-forwarder.foundation_name:
    value: Lab
  .healthwatch-forwarder.health_check_az:
    value: zone-1
  .healthwatch-forwarder.ingestor_instance_count:
    value: 4
  .healthwatch-forwarder.opsman_instance_count:
    value: 2
  .healthwatch-forwarder.publish_to_eva:
    value: true
  .healthwatch-forwarder.worker_instance_count:
    value: 1
  .mysql.skip_name_resolve:
    value: true
  .properties.boshtasks:
    selected_option: enable
    value: enable
  .properties.boshtasks.enable.bosh_taskcheck_password:
    value:
      secret: ((properties_boshtasks_enable_bosh_taskcheck_password.secret))
  .properties.boshtasks.enable.bosh_taskcheck_username:
    value: director
  .properties.indicators_selector:
    selected_option: inactive
    value: "No"
  .properties.opsman:
    selected_option: enable
    value: enable
  .properties.opsman.enable.url:
    value: https://opsman.dell.azure.pivotal.rocks/
  .properties.syslog_selector:
    selected_option: inactive
    value: "No"
resource-config:
  healthwatch-forwarder:
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: false
    max_in_flight: 1
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  mysql:
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: false
    max_in_flight: 1
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  redis:
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: false
    max_in_flight: 1
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
