errand-config:
  delete-all-clusters:
    pre-delete-state: true
  pks-nsx-t-precheck:
    post-deploy-state: false
  smoke-tests:
    post-deploy-state: false
  upgrade-all-service-instances:
    post-deploy-state: true
  wavefront-alert-creation:
    post-deploy-state: false
  wavefront-alert-deletion:
    pre-delete-state: false
network-properties:
  network:
    name: pks
  other_availability_zones:
  - name: zone-1
  - name: zone-2
  - name: zone-3
  service_network:
    name: pks-services
  singleton_availability_zone:
    name: zone-1
product-name: pivotal-container-service
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: ((pivotal-container-service_pks_tls.cert_pem))
      private_key_pem: ((pivotal-container-service_pks_tls.private_key_pem))
  .properties.bosh-metric-sink-etcd:
    value: true
  .properties.bosh-metric-sink-kube-apiserver:
    value: false
  .properties.bosh-metric-sink-kube-controller-manager:
    value: false
  .properties.bosh-metric-sink-kubelet:
    value: false
  .properties.bosh-metric-sink-node-exporter-master:
    value: false
  .properties.bosh-metric-sink-node-exporter-pks-api:
    value: false
  .properties.bosh-metric-sink-node-exporter-worker:
    value: false
  .properties.bosh-metric-sink-outputs:
    value: |
      [[outputs.discard]]
  .properties.cloud_provider:
    selected_option: azure
    value: Azure
  .properties.cloud_provider.azure.azure_cloud_name:
    value: AzurePublicCloud
  .properties.cloud_provider.azure.azure_master_managed_identity:
    value: pks-master
  .properties.cloud_provider.azure.azure_worker_managed_identity:
    value: pks-worker
  .properties.cloud_provider.azure.default_security_group:
    value: dell-pks-api-sg
  .properties.cloud_provider.azure.location:
    value: eastus
  .properties.cloud_provider.azure.primary_availability_set:
    value: dell-pks-as
  .properties.cloud_provider.azure.resource_group_name:
    value: dell
  .properties.cloud_provider.azure.subscription_id:
    value: e1dd1257-8f9a-4cde-8aa3-91ff3e19b874
  .properties.cloud_provider.azure.tenant_id:
    value: 29248f74-371f-4db2-9a50-c62a6877a0c1
  .properties.cloud_provider.azure.vnet_name:
    value: dell-virtual-network
  .properties.cloud_provider.azure.vnet_resource_group_name:
    value: dell
  .properties.log_sink_resources_deploy:
    value: false
  .properties.metric_sink_resources_deploy:
    value: false
  .properties.network_selector:
    selected_option: flannel
    value: flannel
  .properties.network_selector.flannel.pod_network_cidr:
    value: 10.200.0.0/16
  .properties.network_selector.flannel.service_cluster_cidr:
    value: 10.100.200.0/24
  .properties.node_exporter_deploy:
    value: false
  .properties.oidc_selector:
    selected_option: disabled
    value: disabled
  .properties.pks-vrli:
    selected_option: disabled
    value: disabled
  .properties.pks-vrops:
    selected_option: disabled
    value: disabled
  .properties.pks_api_hostname:
    value: api.pks.dell.azure.pivotal.rocks
  .properties.plan1_selector:
    selected_option: active
    value: Plan Active
  .properties.plan1_selector.active.admission_plugins:
    value: []
  .properties.plan1_selector.active.allow_privileged_containers:
    value: false
  .properties.plan1_selector.active.description:
    value: 'Example: This plan will configure a lightweight kubernetes cluster. Not
      recommended for production workloads.'
  .properties.plan1_selector.active.kubelet_drain_delete_local_data:
    value: true
  .properties.plan1_selector.active.kubelet_drain_force:
    value: true
  .properties.plan1_selector.active.kubelet_drain_force_node:
    value: false
  .properties.plan1_selector.active.kubelet_drain_grace_period:
    value: 10
  .properties.plan1_selector.active.kubelet_drain_ignore_daemonsets:
    value: true
  .properties.plan1_selector.active.kubelet_drain_timeout:
    value: 0
  .properties.plan1_selector.active.master_az_placement:
    value:
    - zone-1
    - zone-2
    - zone-3
  .properties.plan1_selector.active.master_instances:
    value: 1
  .properties.plan1_selector.active.max_worker_instances:
    value: 50
  .properties.plan1_selector.active.name:
    value: small
  .properties.plan1_selector.active.worker_az_placement:
    value:
    - zone-1
    - zone-2
    - zone-3
  .properties.plan1_selector.active.worker_instances:
    value: 3
  .properties.plan2_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan3_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan4_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan5_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan6_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan7_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan8_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan9_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan10_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan11_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan12_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan13_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.proxy_selector:
    selected_option: disabled
    value: Disabled
  .properties.syslog_selector:
    selected_option: disabled
    value: disabled
  .properties.telemetry_installation_purpose_selector:
    selected_option: not_provided
    value: not_provided
  .properties.telemetry_selector:
    selected_option: disabled
    value: disabled
  .properties.tmc:
    selected_option: disabled
    value: disabled
  .properties.uaa:
    selected_option: internal
    value: internal
  .properties.uaa_pks_cli_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cli_refresh_token_lifetime:
    value: 21600
  .properties.uaa_pks_cluster_client_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cluster_client_refresh_token_lifetime:
    value: 21600
  .properties.vm_extensions:
    value:
    - public_ip
  .properties.wavefront:
    selected_option: disabled
    value: disabled
  .properties.worker_max_in_flight:
    value: 4
resource-config:
  pivotal-container-service:
    additional_networks: []
    additional_vm_extensions: []
    elb_names:
    - dell-pks-lb
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: false
    max_in_flight: 1
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
